### ISSUE TITLE
Consider 2 x 2 GB

### ISSUE THREAD

**Issue by tommythorn** [daveshah1/TrellisBoard#1]
An ultimate board should IMhO maximize external memory.  Since 2 GiB chips are only ~$13, qty 1, maybe you’d consider going to that?

**Comment by daveshah1** [comment]
What is the source for these chips? I can't find any DDR3/DDR3L 16Gb x16 chips stocked by DigiKey. Going to two 8Gb chips for 2GiB total might be an option, but these seem to be about $26 each on DigiKey so not super cheap. I suspect most applications needing this much memory will be bottlenecked by the maximum clock frequency of the ECP5 anyway.

**Comment by tommythorn** [comment]
I have never used them so I can’t vouch for them, but https://www.components-center.com/product/Micron-Technology-Inc/MT41K1G16DGA-125-A.html

I strongly disagree with your assertion though. If you used this board for running Fedora/RISC-V, then 1 GB is very limiting.  The argument I got from Fedora for why they wouldn’t support 32-bit RISC-V is that they have packages that can barely compile in that little memory.

**Comment by tommythorn** [comment]
Aiee, the qty 1 was a misread, sorry.  It’s qty 1020 but it doesn’t fundamentally change what I wrote.

**Comment by daveshah1** [comment]
Seems like this part is now obsolete - https://media.digikey.com/pdf/PCNs/Micron/PCN-32255.pdf - so probably not a good idea to design it into something new. However, I will consider going up to at least 2GiB (two 8Gb chips) for the next revision as I can see this use case now (although compiling packages that need >1GiB RAM on a 100MHz system doesn't sound like a great deal of fun, adding swap into the equation won't help either)

**Comment by tommythorn** [comment]
Reasonable if you expect to produce more than 500 of these boards, but if they are pin compatible and just a part swap away, I’d personally just stock up and use them.
